---
- hosts: all
  become: yes
  tasks:
    - name: install ufw
      apt:
        name: ufw
        state: latest
        update_cache: yes

    - name: Enable UFW
      ufw:
        state: enabled

    - name: Set logging
      ufw:
        logging: 'on'
        
    - name: Allow all access to tcp ports
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      with_items:  [ '80', '22', '443' ]

    - name: Deny all others
      ufw:
        default: deny
    
    - name: Forward FORWARD
      iptables:
        policy: ACCEPT
        chain: "{{ item }}"
      with_items:  [ 'INPUT', 'OUTPUT', 'FORWARD' ]
    
    # - name: Iptables flush filter
    #   iptables:
    #     flush: yes
    
    - name: restart firewall
      systemd:
        state: restarted
        name: "{{ item }}"
      with_items:  [ 'ufw' ]
