---
- hosts: all
  become: yes
  tasks:
    - name: install ufw
      apt:
        name: ufw
        state: latest
        update_cache: yes

    - name: Enable UFW
      ufw:
        state: enabled

    - name: Set logging
      ufw:
        logging: 'on'

    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: Allow all access to tcp port 443
      ufw:
        rule: allow
        port: '443'
        proto: tcp
        
    - name: Allow all access to tcp port 22
      ufw:
        rule: allow
        port: '22'
        proto: tcp

    - name: Deny all others
      ufw:
        default: deny
