---
- hosts: cloud
  become: yes
  tasks:

    # RCLONE
    
    - name: download rclone script
      get_url:
        url: https://rclone.org/install.sh
        dest: /tmp/install.sh
        mode: 0770

    # - name: install
    #   command: bash /tmp/install.sh

    # - name: create rclone dir
    #   file: 
    #     state: directory
    #     path: /mnt/gdrive
    
    # - name: create rclone config dir
    #   file: 
    #     state: directory
    #     path: /root/.config/rclone
    
    # - name: copy rclone config
    #   template: 
    #     src: templates/rclone.config.j2
    #     dest: /root/.config/rclone/rclone.conf

    # - name: copy rclone service
    #   template: 
    #     src: templates/rclone.service.j2
    #     dest: /etc/systemd/system/rclone.service
    
    # - name: start rclone
    #   systemd:
    #     state: started
    #     name: rclone

    # - name: enable rclone
    #   systemd:
    #     enabled: yes
    #     name: rclone
    
    # - name: get service facts
    #   service_facts:

    # - name: check if rclone is mounted
    #   fail:
    #     msg: rclone not mounted
    #   when: ansible_facts.services['rclone.service'].state != "running"

    # CORNELIUS

    - name: install utils
      apt:
        name: nfs-common
        state: latest
        update_cache: yes

    - name: create cache dir
      file: 
        state: directory
        path: /mnt/cache
    
    - name: mount cache share
      mount:
        fstype: nfs
        opts: defaults
        dump: 0
        passno: 0
        state: mounted
        src: 10.253.0.1:/mnt/user/Speed
        path: /mnt/cache
    
    - name: create cache dir
      file: 
        state: directory
        path: /mnt/media
    
    - name: mount media share
      mount:
        fstype: nfs
        opts: defaults
        dump: 0
        passno: 0
        state: mounted
        src: 10.253.0.1:/mnt/user/Media
        path: /mnt/media
