- name: Fetch a backup of a postgres DB that runs on a remote docker container
  hosts: library
  gather_facts: yes
  become: yes

  tasks:
    - name: Set backup_dir and db_dump_name variable
      set_fact:
        backup_dir: /tmp/bkups
        db_dump_name: librarydb-{{ ansible_date_time.date }}.bkp
        local_backup_dir: /home/riley/Documents

    - name: Make sure backup directory exists on the local machine
      file:
        state: directory
        path: "{{ backup_dir }}"

    - name: Dump the DB to a bind-mounted volume
      command: docker exec -i --user postgres librarydb bash -c "pg_dump -Fc library" > /tmp/ps.bkup

    - name: Fetch the dumped DB from remote to local
      fetch:
        src: "{{ backup_dir }}/{{ db_dump_name }}"
        dest: "{{ local_backup_dir }}/"
        flat: yes