---
- hosts: all
  become: yes
  tasks:
    - name: install wireguard
      apt:
        name: wireguard
        state: latest
        update_cache: yes

    - name: copy wireguard config
      template: 
        src: templates/spoke.conf.j2
        dest: "/etc/wireguard/wg0.conf"

    - name: start wireguard
      systemd:
        state: started
        name: wg-quick@wg0

    - name: enable wireguard
      systemd:
        enabled: yes
        name: wg-quick@wg0

    - name: update wg cron
      cron:
        name: "update wg"
        minute: "10"
        hour: "*"
        job: "systemctl restart wg-quick@wg0.service"
